### ISSUE TITLE
Always getting "403 Forbidden" error.

### ISSUE THREAD

**Issue by rvega** [All-About-Berlin/burgeramt-appointments#22]
Running the appointment finder, either from your website, or from a command line per the instructions in this repo, I always get a 403 error.

An additional question: for the BOOKING_TOOL_ID and BOOKING_TOOL_EMAIL variables, are these values supposed to be obtained or registered from the city of Berlin? From where? 

Thanks!

**Comment by nicbou** [comment]
Berlin has been blocking everything since a few days. There is nothing I can do about it unfortunately.

These values are used to identify you. They don't need to be registered or anything. They're just used to tell bots apart.

**Comment by themaxw** [comment]
Is there a reason why the tool on the website still works, while running it yourself gives an error?

**Comment by nicbou** [comment]
Please check previous issues as this was already addressed.

**Comment by Tim4497** [comment]
I was able to use the CLI tool by setting my own User-Agent in the `appointments.py` prior to running it locally. I used the User-Agent I also send to the official `https://service.berlin.de/terminvereinbarung/termin/taken/`. I'm not sure how legal this is, as @nicbou mentioned you have to send your email with this header... But who cares?

**Comment by nicbou** [comment]
@Tim4497, *I* care. We started getting 403 and 418 errors because people disregarded the rules set by Berlin.de when modifying my script. The end result is that everyone gets blocked, and that we can no longer offer tools to help Berliners.

Keep that in mind when making modifications to the user agent or polling rate.
